toto_totalizer:
    resource: "@TotoTotalizerBundle/Controller/"
    type:     annotation
    prefix:   /

estina_core:
    resource: "@TotoCoreBundle/Controller/"
    type:     annotation
    prefix:   /

