parameters:
    toto_import_cache: %kernel.cache_dir%/toto_import

services:
    toto_import.result_importer.eurobasket2013:
        class: Toto\ImportBundle\ResultImporter\Eurobasket2013Importer
        arguments: 
            - @totalizer.game_service
            - @totalizer.tournament_service
            - @totalizer.team_service
            - %toto_import_cache%

    toto_import.game_importer.eurobasket2013:
        class: Toto\ImportBundle\GameImporter\Eurobasket2013Importer
        arguments: 
            - @totalizer.game_service
            - @totalizer.tournament_service
            - @totalizer.team_service
            - %toto_import_cache%

